create_clock -name core_clk -period 10.0 [get_ports clk]
set_clock_uncertainty -setup 0.10 [get_clocks core_clk]
set_input_delay -clock core_clk -max 0.50 [get_ports {instr* data_read_data* reset}]
set_input_delay -clock core_clk -min 0.00 [get_ports {instr* data_read_data* reset}]
set_input_transition 0.05 [get_ports {instr* data_read_data* reset}]
set_output_delay -clock core_clk -max 0.50 [get_ports {current_pc* data_addr* data_write_data* data_write_en data_write_strb* retire_valid retire_pc* cycle_count* retired_count*}]
set_output_delay -clock core_clk -min 0.00 [get_ports {current_pc* data_addr* data_write_data* data_write_en data_write_strb* retire_valid retire_pc* cycle_count* retired_count*}]
set_load 5.0 [get_ports {current_pc* data_addr* data_write_data* data_write_en data_write_strb* retire_valid retire_pc* cycle_count* retired_count*}]
